apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: byotf-web-app
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Create a simple web app
    source:
      repo: https://github.com/sadiwala/byotf-web-app.git
      sourceType: git
    version: 0.0.0
    description: {}
  content: {}
  interfaces: {}
